Nc news 4
HaithemLO/nv-news pull request #3
Opened 2023-08-15 13:24 UTC by HaithemLO

renamed named it to nc-news 4 to match the sprint

2023-08-15 14:06 UTC, Pipe-Smoking-Rabbit requested changes
Really good work on this ticket, I've left some feedback to have a look at on the code. One thing that is missing I noticed is any tests for errors, what would we expect if:
- The _article_id_ is a number that can't be found in the data base, such as `99999` ?
- The _article_id_ is the wrong data type, _"/api/articles/banana"_ ?

2023-08-15 14:06 UTC, Pipe-Smoking-Rabbit commented on models/model.js
> +        return rows[0];
Very good model function! Good check for empty rows to send a _Promise.reject_ and good use of the `$` binding 🏆

2023-08-15 14:06 UTC, Pipe-Smoking-Rabbit commented on controller/controller.js
> +      .catch(next);
Great controller! That's a lovely syntax for the catch using `.catch(next)` - but then it doesn't look like anything is happening with that error, how should we handle the error in the _app.js_ ?

2023-08-16 10:24 UTC, Hard-Luck requested changes
just a couple of changes to make

2023-08-16 10:24 UTC, Hard-Luck commented on __tests__/app.test.js
> +        expect(res.body.topics.length).not.toBe(0)
We can be more specific here, look in the database test data and check what the length should

2023-08-16 10:24 UTC, Hard-Luck commented on __tests__/app.test.js
> +      .expect(404);
We should also expect a message served back to us with the 404

2023-08-16 10:24 UTC, Hard-Luck commented on __tests__/app.test.js
> +      .expect(404);
This would be a 400 as the user would have made a bad request

2023-08-16 11:36 UTC, Keb84 approved these changes
Nice work. Merge when ready 🙂

2023-08-16 13:58 UTC, merged